# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ci-pipeline

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  publishFolder: 'prod'

steps:
- task: DotNetCoreCLI@2
  displayName: Build ASP.NET core app
  inputs:
    command: publish
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) -o out'
