# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ci-pipeline

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  publishFolder: 'prod'

steps:
- script: dotnet run --project ./aspnetapp/aspnetapp.csproj
  displayName: 'Run .NET core app'
- task: DotNetCoreCLI@2
  displayName: Run ASP.NET core app
  inputs:
    command: run
    projects: '**/*.csproj'
    arguments: '--project ./home/vsts/work/1/s/aspnetapp/aspnetapp.csproj'
