# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ci-pipeline

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  publishFolder: 'prod'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.0.0'
- script: dotnet restore
  displayName: 'dotnet restore'
- script: dotnet publish -c $(buildConfiguration) -o $(publishFolder)
  displayName: 'dotnet publish $(buildConfiguration) to $(publishFolder)'
